### ISSUE TITLE
`resolve-bin` doesn't resolve globally installed phantomjs

### ISSUE THREAD

**Issue by alexindigo** [busterjs/grunt-buster#31]
But maybe the right solution would be to use `buster-server -c`.

**Comment by dominykas** [comment]
Did you install it with `npm install -g phantomjs` or did you use some other way?

**Comment by alexindigo** [comment]
Short answer: Yes.

Long answer: We're using docker containers for development with built-in dependencies such as phantomjs, sass, etc.

**Comment by dominykas** [comment]
Yes with npm or yes some other way? ;) If its installed with npm - it might not work if not all paths are set, ie do any other global modules work at all, esp. in headless shells?

If it's not installed via npm - it won't be seen, alright, but maybe it's then worth PRing resolve-bin to also use binaries in the PATH?

**Comment by alexindigo** [comment]
Oh you're right, we don't use npm to install phantom :)

This is the Dockerfile – https://github.com/alexindigo/docker-trulia-rendr-base/blob/master/Dockerfile
Then phantomjs available in the PATH.

**Comment by dominykas** [comment]
Can I simply PR that to install via npm? :D

**Comment by alexindigo** [comment]
There are many ways to install phantomjs on box, so having this package working in more environments will be beneficial for the package itself. :)

**Comment by dominykas** [comment]
OK, looks like it's not even possible to `require()` phantomjs without setting `NODE_PATH` - which is why it works for me locally. However: https://docs.npmjs.com/misc/faq#i-installed-something-globally-but-i-can-t-require-it

Will try to PR/fix today.

**Comment by dominykas** [comment]
Published as 0.4
