### ISSUE TITLE
I want t use reporter as 'specification but it's dones'nt work

### ISSUE THREAD

**Issue by rlanore** [busterjs/grunt-buster#32]
gruntfile as

        buster: {
            options: {
                reporter: 'specification'
            },
            test: {
                config: 'test/buster.js'
            }
        },

How to achieve this ?

**Comment by dominykas** [comment]
I believe the correct way is to do it something like this:

```js
"buster": {
    "dist": {
        "test": {
            // opions for `buster-test` command in the `dist` target
            "reporter": "specification"
        }
    }
}
```

At least that's what works for me: https://github.com/h5o/h5o-js/blob/master/Gruntfile.js#L35

**Comment by dominykas** [comment]
No input for 9 months - closing.
